[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Le code serveur n'a pas à être servi comme fichier du site
[[redirects]]
  from = "/netlify/*"
  to = "/404"
  status = 404
  force = true
